modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
logoFile="logo.png"
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
credits = "Alessandra15204 - Italian localisation"

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId="ntgl"
mandatory=true
versionRange="[1.20.1-3.0.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies."${mod_id}"]]
modId="create"
mandatory=true
versionRange="[0.5.1.f-26,)"
ordering="AFTER"
side="BOTH"